### ISSUE TITLE
Matt Mets' temperature commits break cupcake heated buildplatform thermistor

### ISSUE THREAD

**Issue by koenkooi** [makerbot/G3Firmware#66]
After updating my extruder fw from last weeks git to todays git I my hbp doesn't turn on anymore.

If I then do 'git rebase -i 7f8a6c7234559e6b38067a25f45716d50c14a23e' and remove all temp commits and the toolstatus one everything works as expected again.

**Comment by kintel** [comment]
I just discovered this yesterday and Matt is on the case.
A quick workaround for now is to comment out line 111 in v2/src/Extruder/Heater.cc:
// fail();

**Comment by cibomahto** [comment]
Sorry about that! I think I've addressed this in #69. I tested the code both on the gen4 electronics with a thermocouple-based extruder and heated build platform, and on gen 3 with thermistor extruder and heated build platform.
